### ISSUE TITLE
Update Guzzle to the latest version

### ISSUE THREAD

**Issue by theKhorshed** [clickonmedia/frameio-php-client#1]
Hi there, 

Thanks for the nice API client. I'm using this with Laravel but it seems not compatible with the latest version of Laravel because of Guzzle incompatibility. 

I would love to make a PR if you agree to update Guzzle to the latest version. 

Thanks
Khorshed

**Comment by jpylisela** [comment]
Hi,

please do, thanks.

Juha

to 7. tammik. 2021 klo 9.45 Khorshed Alam (notifications@github.com)
kirjoitti:

**Comment by theKhorshed** [comment]
Hi @jpylisela,

I have made a pull request #2 . Let me know if that's good or you want any changes.

Thanks
